### ISSUE TITLE
Контейнер не собирается из-за пакета pkg-resource

### ISSUE THREAD

**Issue by XenoAura** [blohinn/telegram-avito-bot#1]
https://github.com/blohinn/telegram-avito-bot/blob/a396c1f8c1dd1ddb9ce94360b67ce996b1cc7d26/requirements.txt#L12

env:
> Ubuntu 18.04.1 LTS
> Docker version 18.09.0, build 4d60db4
> docker-compose version 1.23.1, build b02f1306

При сборке контейнера вываливается ошибка следующая ошибка.
`Collecting pkg-resources==0.0.0 (from -r ./requirements.txt (line 12))
  Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r ./requirements.txt (line 12)) (from versions: )
No matching distribution found for pkg-resources==0.0.0 (from -r ./requirements.txt (line 12))
ERROR: Service 'updates' failed to build: The command '/bin/sh -c pip install -r ./requirements.txt' returned a non-zero code: 1`

При удалении этого пакета из requirements.txt все проходит нормально.

**Comment by blohinn** [comment]
Благодарю.
